In [6]:
# Install openrouteservice for first time users
# !pip install openrouteservice

In [7]:
import openrouteservice
import pandas as pd
import numpy as np
from tqdm import tqdm

In [8]:
# Load in rental data
rental = pd.read_csv("rea_data/domain/Data/vic_rentals_all_cleaned.csv")
rental_coords = rental[["listing_id", "lon","lat"]]
rental_coords.head()

   listing_id        lon        lat
0    16782629  144.87091 -37.830982
1    17471867  144.86755 -37.826218
2    17721851  144.86632 -37.831226
3    17725855  144.86768 -37.827423
4    17745057  144.86790 -37.826270

In [9]:
# Load in bus stop data
bus = pd.read_csv("data\metro_bus_stops.txt")
bus_coords = bus[["stop_id", "stop_lon","stop_lat"]]
bus_coords.head()

  stop_id    stop_lon   stop_lat
0    1000  145.018951 -37.700775
1   10001  144.776152 -37.726975
2   10002  144.595789 -37.676159
3   10009  144.775899 -37.741497
4    1001  145.019685 -37.699183

In [10]:
# Define Haversine distance function
def haversine_vec(lon1, lat1, lon2, lat2):
    """
    Compute distance (meters) between two points using vectorised Haversine formula
    """
    lon1_rad = np.radians(lon1)[:, np.newaxis]
    lat1_rad = np.radians(lat1)[:, np.newaxis]

    lon2_rad = np.radians(lon2)[np.newaxis, :]
    lat2_rad = np.radians(lat2)[np.newaxis, :]

    earth_mean_radius = 6371000
    phi1, phi2 = lat1_rad, lat2_rad
    dphi1 = lat2_rad - lat1_rad
    dlambda = lon2_rad - lon1_rad
    
    a = np.sin(dphi1/2)**2 + np.cos(phi1)*np.cos(phi2)*np.sin(dlambda/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))

    return earth_mean_radius * c

In [11]:
# Find top 5 closest bus stops for each rental
dist_matrix = haversine_vec(rental_coords["lon"].values, rental_coords["lat"].values, bus_coords["stop_lon"].values, bus_coords["stop_lat"].values)

top5_indices = np.argsort(dist_matrix, axis=1)[:,:5]

rental_coords["top5_idx"] = list(top5_indices)
rental_coords["top5_tuple"] = [tuple(int(i) for i in sorted(x)) for x in top5_indices]

C:\Users\chinj\AppData\Local\Temp\ipykernel_9356\1667537328.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rental_coords["top5_idx"] = list(top5_indices)
C:\Users\chinj\AppData\Local\Temp\ipykernel_9356\1667537328.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rental_coords["top5_tuple"] = [tuple(int(i) for i in sorted(x)) for x in top5_indices]

In [12]:
# Group results by their top 5 closest bus stops
groups = rental_coords.groupby("top5_tuple")["listing_id"].apply(list).reset_index()
groups["num_rentals"] = groups["listing_id"].apply(len)

In [13]:
# API key for OpenRouteService (ORS); hidden here for privacy
API_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImEyMGE4NjZkNjYyZDQ4NDdiN2I4ODJhOWQ1ODM0YThhIiwiaCI6Im11cm11cjY0In0=" # Replace NA with your actual key when running

# Initialize ORS client with the API key
client = openrouteservice.Client(key = API_KEY)

In [14]:
# Batch rentals to stay under API route limit
top_n_bus = 5
max_route_per_batch = 3500

batches = []
current_batch = []
current_batch_rentals = 0

# Loop over each group of rentals that share the same top 5 bus stops
for _, row in groups.iterrows():
    group_name = row["top5_tuple"]
    rentals = row["listing_id"]
    group_size = len(rentals)

    start = 0
    # Split group into chunks so that adding them won't exceed ORS route limit
    while start < group_size:
        # Estimate number of rentals allowed to add to current batch without exceeding ORS route limit
        num_groups_if_added = len(current_batch) + 1
        max_rentals_for_this_chunk = max(
            (max_route_per_batch // (num_groups_if_added * top_n_bus)) - current_batch_rentals,
            1
        )

        # Determine slice of rentals for this chunk
        end = min(start + max_rentals_for_this_chunk, group_size)
        chunk = rentals[start:end]

        # Compute estimated number of routes if this chunk is added
        num_origins = current_batch_rentals + len(chunk)
        num_destinations = num_groups_if_added * top_n_bus
        estimated_routes = num_origins * num_destinations

        # Start new batch if adding this chunk exceeds ORS route limit
        if estimated_routes >= max_route_per_batch: 
            if current_batch:
                batches.append(current_batch)
            current_batch = [(group_name, chunk)]     
            current_batch_rentals = len(chunk)
        else:
            # Add chunk to batch otherwise
            current_batch.append((group_name, chunk))
            current_batch_rentals += len(chunk)
        start = end

# Append last batch if there are any remaining rentals
if current_batch:
        batches.append(current_batch)

print(f"Created {len(batches)} batches with full ORS route limit logic.")

Created 308 batches with full ORS route limit logic.

In [15]:
# Print and check summary of batches
for i, batch in enumerate(batches):
    num_groups = len(batch)
    num_rentals = sum(len(rentals) for _, rentals in batch)
    print(f"Batch {i+1}: {num_groups} groups, {num_rentals} rentals")

Batch 1: 25 groups, 26 rentals
Batch 2: 21 groups, 33 rentals
Batch 3: 19 groups, 32 rentals
Batch 4: 22 groups, 30 rentals
Batch 5: 22 groups, 30 rentals
Batch 6: 25 groups, 26 rentals
Batch 7: 24 groups, 28 rentals
Batch 8: 24 groups, 29 rentals
Batch 9: 21 groups, 31 rentals
Batch 10: 21 groups, 32 rentals
Batch 11: 21 groups, 32 rentals
Batch 12: 24 groups, 27 rentals
Batch 13: 23 groups, 29 rentals
Batch 14: 24 groups, 27 rentals
Batch 15: 20 groups, 33 rentals
Batch 16: 25 groups, 27 rentals
Batch 17: 21 groups, 33 rentals
Batch 18: 22 groups, 30 rentals
Batch 19: 22 groups, 30 rentals
Batch 20: 23 groups, 29 rentals
Batch 21: 25 groups, 27 rentals
Batch 22: 24 groups, 29 rentals
Batch 23: 21 groups, 31 rentals
Batch 24: 24 groups, 28 rentals
Batch 25: 24 groups, 29 rentals
Batch 26: 15 groups, 43 rentals
Batch 27: 23 groups, 29 rentals
Batch 28: 20 groups, 34 rentals
Batch 29: 23 groups, 30 rentals
Batch 30: 22 groups, 31 rentals
Batch 31: 19 groups, 34 rentals
Batch 32: 15 groups, 46 rentals
Batch 33: 15 groups, 45 rentals
Batch 34: 20 groups, 34 rentals
Batch 35: 17 groups, 40 rentals
Batch 36: 22 groups, 31 rentals
Batch 37: 18 groups, 38 rentals
Batch 38: 19 groups, 36 rentals
Batch 39: 17 groups, 38 rentals
Batch 40: 19 groups, 34 rentals
Batch 41: 22 groups, 30 rentals
Batch 42: 25 groups, 26 rentals
Batch 43: 22 groups, 31 rentals
Batch 44: 24 groups, 28 rentals
Batch 45: 21 groups, 33 rentals
Batch 46: 18 groups, 37 rentals
Batch 47: 22 groups, 30 rentals
Batch 48: 21 groups, 31 rentals
Batch 49: 24 groups, 28 rentals
Batch 50: 23 groups, 29 rentals
Batch 51: 24 groups, 27 rentals
Batch 52: 24 groups, 27 rentals
Batch 53: 23 groups, 29 rentals
Batch 54: 19 groups, 19 rentals
Batch 55: 2 groups, 243 rentals
Batch 56: 14 groups, 46 rentals
Batch 57: 24 groups, 29 rentals
Batch 58: 24 groups, 27 rentals
Batch 59: 24 groups, 27 rentals
Batch 60: 18 groups, 37 rentals
Batch 61: 21 groups, 31 rentals
Batch 62: 25 groups, 26 rentals
Batch 63: 21 groups, 33 rentals
Batch 64: 22 groups, 30 rentals
Batch 65: 24 groups, 27 rentals
Batch 66: 24 groups, 29 rentals
Batch 67: 24 groups, 27 rentals
Batch 68: 24 groups, 29 rentals
Batch 69: 24 groups, 27 rentals
Batch 70: 24 groups, 27 rentals
Batch 71: 25 groups, 27 rentals
Batch 72: 24 groups, 26 rentals
Batch 73: 20 groups, 33 rentals
Batch 74: 16 groups, 43 rentals
Batch 75: 15 groups, 43 rentals
Batch 76: 23 groups, 30 rentals
Batch 77: 15 groups, 46 rentals
Batch 78: 24 groups, 27 rentals
Batch 79: 19 groups, 36 rentals
Batch 80: 24 groups, 27 rentals
Batch 81: 24 groups, 27 rentals
Batch 82: 24 groups, 28 rentals
Batch 83: 17 groups, 41 rentals
Batch 84: 17 groups, 38 rentals
Batch 85: 19 groups, 35 rentals
Batch 86: 22 groups, 31 rentals
Batch 87: 24 groups, 28 rentals
Batch 88: 21 groups, 33 rentals
Batch 89: 24 groups, 29 rentals
Batch 90: 16 groups, 43 rentals
Batch 91: 24 groups, 27 rentals
Batch 92: 22 groups, 30 rentals
Batch 93: 25 groups, 27 rentals
Batch 94: 24 groups, 27 rentals
Batch 95: 26 groups, 26 rentals
Batch 96: 24 groups, 29 rentals
Batch 97: 25 groups, 27 rentals
Batch 98: 19 groups, 34 rentals
Batch 99: 21 groups, 33 rentals
Batch 100: 15 groups, 46 rentals
Batch 101: 25 groups, 27 rentals
Batch 102: 24 groups, 29 rentals
Batch 103: 24 groups, 27 rentals
Batch 104: 23 groups, 29 rentals
Batch 105: 24 groups, 29 rentals
Batch 106: 24 groups, 28 rentals
Batch 107: 18 groups, 38 rentals
Batch 108: 15 groups, 43 rentals
Batch 109: 24 groups, 27 rentals
Batch 110: 24 groups, 29 rentals
Batch 111: 25 groups, 27 rentals
Batch 112: 25 groups, 27 rentals
Batch 113: 22 groups, 30 rentals
Batch 114: 22 groups, 31 rentals
Batch 115: 21 groups, 31 rentals
Batch 116: 22 groups, 31 rentals
Batch 117: 19 groups, 35 rentals
Batch 118: 21 groups, 33 rentals
Batch 119: 19 groups, 33 rentals
Batch 120: 24 groups, 29 rentals
Batch 121: 25 groups, 27 rentals
Batch 122: 24 groups, 29 rentals
Batch 123: 25 groups, 27 rentals
Batch 124: 24 groups, 28 rentals
Batch 125: 25 groups, 27 rentals
Batch 126: 25 groups, 27 rentals
Batch 127: 24 groups, 27 rentals
Batch 128: 24 groups, 28 rentals
Batch 129: 23 groups, 29 rentals
Batch 130: 18 groups, 36 rentals
Batch 131: 22 groups, 30 rentals
Batch 132: 19 groups, 34 rentals
Batch 133: 11 groups, 63 rentals
Batch 134: 17 groups, 41 rentals
Batch 135: 22 groups, 30 rentals
Batch 136: 13 groups, 40 rentals
Batch 137: 12 groups, 58 rentals
Batch 138: 13 groups, 52 rentals
Batch 139: 14 groups, 46 rentals
Batch 140: 14 groups, 49 rentals
Batch 141: 17 groups, 38 rentals
Batch 142: 19 groups, 36 rentals
Batch 143: 8 groups, 83 rentals
Batch 144: 24 groups, 27 rentals
Batch 145: 22 groups, 31 rentals
Batch 146: 18 groups, 37 rentals
Batch 147: 14 groups, 49 rentals
Batch 148: 15 groups, 45 rentals
Batch 149: 23 groups, 30 rentals
Batch 150: 15 groups, 46 rentals
Batch 151: 9 groups, 77 rentals
Batch 152: 9 groups, 55 rentals
Batch 153: 16 groups, 42 rentals
Batch 154: 14 groups, 47 rentals
Batch 155: 24 groups, 28 rentals
Batch 156: 17 groups, 41 rentals
Batch 157: 8 groups, 77 rentals
Batch 158: 18 groups, 38 rentals
Batch 159: 24 groups, 29 rentals
Batch 160: 20 groups, 33 rentals
Batch 161: 23 groups, 30 rentals
Batch 162: 19 groups, 34 rentals
Batch 163: 22 groups, 30 rentals
Batch 164: 24 groups, 28 rentals
Batch 165: 9 groups, 77 rentals
Batch 166: 17 groups, 39 rentals
Batch 167: 23 groups, 30 rentals
Batch 168: 16 groups, 41 rentals
Batch 169: 24 groups, 27 rentals
Batch 170: 24 groups, 27 rentals
Batch 171: 17 groups, 40 rentals
Batch 172: 23 groups, 30 rentals
Batch 173: 23 groups, 29 rentals
Batch 174: 9 groups, 9 rentals
Batch 175: 3 groups, 233 rentals
Batch 176: 8 groups, 87 rentals
Batch 177: 19 groups, 36 rentals
Batch 178: 24 groups, 27 rentals
Batch 179: 24 groups, 28 rentals
Batch 180: 16 groups, 42 rentals
Batch 181: 23 groups, 30 rentals
Batch 182: 23 groups, 29 rentals
Batch 183: 24 groups, 29 rentals
Batch 184: 9 groups, 69 rentals
Batch 185: 6 groups, 111 rentals
Batch 186: 23 groups, 29 rentals
Batch 187: 18 groups, 38 rentals
Batch 188: 6 groups, 111 rentals
Batch 189: 24 groups, 27 rentals
Batch 190: 23 groups, 29 rentals
Batch 191: 24 groups, 29 rentals
Batch 192: 20 groups, 33 rentals
Batch 193: 19 groups, 23 rentals
Batch 194: 6 groups, 114 rentals
Batch 195: 16 groups, 41 rentals
Batch 196: 15 groups, 46 rentals
Batch 197: 14 groups, 48 rentals
Batch 198: 18 groups, 38 rentals
Batch 199: 15 groups, 46 rentals
Batch 200: 12 groups, 58 rentals
Batch 201: 6 groups, 108 rentals
Batch 202: 15 groups, 45 rentals
Batch 203: 17 groups, 39 rentals
Batch 204: 19 groups, 36 rentals
Batch 205: 19 groups, 30 rentals
Batch 206: 14 groups, 49 rentals
Batch 207: 16 groups, 41 rentals
Batch 208: 14 groups, 46 rentals
Batch 209: 16 groups, 41 rentals
Batch 210: 16 groups, 42 rentals
Batch 211: 17 groups, 38 rentals
Batch 212: 18 groups, 38 rentals
Batch 213: 23 groups, 30 rentals
Batch 214: 22 groups, 31 rentals
Batch 215: 18 groups, 38 rentals
Batch 216: 17 groups, 38 rentals
Batch 217: 22 groups, 30 rentals
Batch 218: 14 groups, 48 rentals
Batch 219: 10 groups, 69 rentals
Batch 220: 20 groups, 34 rentals
Batch 221: 20 groups, 33 rentals
Batch 222: 23 groups, 29 rentals
Batch 223: 24 groups, 28 rentals
Batch 224: 22 groups, 30 rentals
Batch 225: 24 groups, 27 rentals
Batch 226: 21 groups, 31 rentals
Batch 227: 17 groups, 39 rentals
Batch 228: 19 groups, 33 rentals
Batch 229: 12 groups, 54 rentals
Batch 230: 19 groups, 35 rentals
Batch 231: 21 groups, 32 rentals
Batch 232: 23 groups, 29 rentals
Batch 233: 17 groups, 39 rentals
Batch 234: 24 groups, 29 rentals
Batch 235: 19 groups, 36 rentals
Batch 236: 17 groups, 40 rentals
Batch 237: 17 groups, 38 rentals
Batch 238: 20 groups, 33 rentals
Batch 239: 24 groups, 28 rentals
Batch 240: 24 groups, 28 rentals
Batch 241: 11 groups, 61 rentals
Batch 242: 21 groups, 32 rentals
Batch 243: 20 groups, 34 rentals
Batch 244: 24 groups, 29 rentals
Batch 245: 25 groups, 26 rentals
Batch 246: 19 groups, 36 rentals
Batch 247: 4 groups, 161 rentals
Batch 248: 24 groups, 27 rentals
Batch 249: 22 groups, 31 rentals
Batch 250: 22 groups, 30 rentals
Batch 251: 25 groups, 27 rentals
Batch 252: 22 groups, 30 rentals
Batch 253: 23 groups, 30 rentals
Batch 254: 19 groups, 35 rentals
Batch 255: 20 groups, 33 rentals
Batch 256: 24 groups, 29 rentals
Batch 257: 19 groups, 34 rentals
Batch 258: 22 groups, 30 rentals
Batch 259: 24 groups, 28 rentals
Batch 260: 24 groups, 29 rentals
Batch 261: 23 groups, 30 rentals
Batch 262: 19 groups, 33 rentals
Batch 263: 15 groups, 46 rentals
Batch 264: 20 groups, 33 rentals
Batch 265: 18 groups, 38 rentals
Batch 266: 23 groups, 30 rentals
Batch 267: 21 groups, 31 rentals
Batch 268: 24 groups, 27 rentals
Batch 269: 19 groups, 35 rentals
Batch 270: 21 groups, 31 rentals
Batch 271: 19 groups, 35 rentals
Batch 272: 18 groups, 36 rentals
Batch 273: 15 groups, 46 rentals
Batch 274: 19 groups, 35 rentals
Batch 275: 22 groups, 30 rentals
Batch 276: 10 groups, 64 rentals
Batch 277: 5 groups, 137 rentals
Batch 278: 8 groups, 79 rentals
Batch 279: 21 groups, 33 rentals
Batch 280: 19 groups, 35 rentals
Batch 281: 24 groups, 29 rentals
Batch 282: 22 groups, 30 rentals
Batch 283: 23 groups, 30 rentals
Batch 284: 20 groups, 33 rentals
Batch 285: 14 groups, 47 rentals
Batch 286: 24 groups, 26 rentals
Batch 287: 25 groups, 27 rentals
Batch 288: 22 groups, 31 rentals
Batch 289: 21 groups, 32 rentals
Batch 290: 24 groups, 29 rentals
Batch 291: 21 groups, 33 rentals
Batch 292: 21 groups, 33 rentals
Batch 293: 14 groups, 49 rentals
Batch 294: 16 groups, 43 rentals
Batch 295: 17 groups, 41 rentals
Batch 296: 25 groups, 27 rentals
Batch 297: 24 groups, 29 rentals
Batch 298: 24 groups, 27 rentals
Batch 299: 19 groups, 36 rentals
Batch 300: 10 groups, 68 rentals
Batch 301: 22 groups, 30 rentals
Batch 302: 24 groups, 29 rentals
Batch 303: 22 groups, 30 rentals
Batch 304: 19 groups, 35 rentals
Batch 305: 20 groups, 34 rentals
Batch 306: 22 groups, 31 rentals
Batch 307: 20 groups, 34 rentals
Batch 308: 19 groups, 27 rentals

In [16]:
# Call ORS to get distance to closest bus stops
all_rental_ids = []
all_distances = []
all_bus_ids = []

for batch in tqdm(batches, desc="Processing batches"):
    batch_rentals = [r for _, rentals in batch for r in rentals]
    batch_coords = rental_coords.set_index("listing_id").loc[batch_rentals][["lon", "lat"]].values.tolist()

    batch_bus_indices = [
        rental_coords.loc[rental_coords["listing_id"]==r, "top5_idx"].values[0] for r in batch_rentals
    ]

    unique_bus_indices = list(set(idx for indices in batch_bus_indices for idx in indices))

    origins = batch_coords
    destinations = bus_coords.loc[bus_coords.index.isin(unique_bus_indices)][["stop_lon", "stop_lat"]].values.tolist()
    dest_ids_map = {idx: bus_coords["stop_id"].iloc[idx] for idx in unique_bus_indices}
   
    bus_pos_map = {idx: i for i, idx in enumerate(unique_bus_indices)}

    num_origins = len(origins)
    num_destinations = len(destinations)
    num_routes = num_origins * num_destinations
    print(f"Checking batch → {num_origins} origins × {num_destinations} destinations = {num_routes} routes")

    break

    # Call ORS distance matrix
    matrix = client.distance_matrix(
        locations = origins + destinations,
        profile = "driving-car",
        metrics = ["distance"],
        sources = list(range(len(origins))),
        destinations = list(range(len(origins), len(origins)+len(destinations)))
    )

    # Extract distances and bus stop IDs for top 5 bus stops
    for i, rental in enumerate(batch_rentals):
        top_indices = batch_bus_indices[i]
        dest_positions = [bus_pos_map[idx] for idx in top_indices]
        rental_distances = [matrix["distances"][i][pos] for pos in dest_positions]
        rental_bus_ids = [dest_ids_map[idx] for idx in top_indices]

        sorted_idx = np.argsort(rental_distances)
        top_n_distances = [rental_distances[k] for k in sorted_idx]
        top_n_ids = [rental_bus_ids[k] for k in sorted_idx]

        all_rental_ids.append(batch_rentals[i])
        all_distances.append(top_n_distances)
        all_bus_ids.append(top_n_ids)

Processing batches:   0%|          | 0/308 [00:00<?, ?it/s]

Checking batch → 26 origins × 77 destinations = 2002 routes

In [17]:
# Save ORS distances for bus stops into dataframe
df = pd.DataFrame({
    "rental_id": all_rental_ids,
    "top_distances": all_distances,
    "top_bus_ids": all_bus_ids
})

df.head()

Empty DataFrame
Columns: [rental_id, top_distances, top_bus_ids]
Index: []

In [18]:
# Save final CSV
df.to_csv("rentals_distances_to_bus_stops.csv", index=False)